### ISSUE TITLE
[Help Wanted] Update & Redesign

### ISSUE THREAD

**Issue by fedebotu** [kaist-silab/rl4co-homepage#1]
We would like to give the RL4CO homepage updates and a fresh look!

## Content
- [ ] **General content**: update content to the latest version

## Redesign
- [ ] **Modularization**: so that we don't have to add hardcoded HTML code (e.g. modifying template websites)
- [ ] **Copy-paste button**: `pip install rl4co` and the citation must be easy to copy and paste

---

Your help is needed: feel free to drop in ideas!

**Comment by DavideTr8** [comment]
As discussed, I can give a bit of help to set up a template (we can decide together the new style)

**Comment by fedebotu** [comment]
Done, transferred to RL4CO `gh-pages` branch!
